#lang sicp

(define (make-account balance password)
  (let ((consec-incorrect 0))
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
                 balance)
          "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (call-the-cops . x)
      "Call the cops")
    (define (dispatch p m)
      (cond ((>= consec-incorrect 7) call-the-cops)
            ((eq? p password)
             (set! consec-incorrect 0)
             (cond ((eq? m 'withdraw) withdraw)
                   ((eq? m 'deposit) deposit)
                   (else (error "Unknown request: MAKE-ACCOUNT"
                                m))))
            (else (set! consec-incorrect (+ consec-incorrect 1))
                  (lambda x "Incorrect password"))))
    dispatch))
